-- CAFE MOCA offline keyword match integration
-- Run this once in the SAME Supabase project used by moca-survey-online.

create table if not exists public.moca_offline_keyword_responses (
  id bigint generated by default as identity primary key,
  participant_id uuid not null references public.moca_survey_participants(id) on delete cascade,
  student_id text not null,
  cafe_index smallint not null check (cafe_index between 1 and 6),
  selected_keywords jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(participant_id, cafe_index)
);

create index if not exists moca_offline_keyword_student_idx
  on public.moca_offline_keyword_responses(student_id);

alter table public.moca_offline_keyword_responses enable row level security;

-- Direct client access stays blocked.
-- Offline clients use the SECURITY DEFINER RPC functions below.

create or replace function public.check_moca_offline_eligibility(p_student_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.moca_survey_participants%rowtype;
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  if nullif(trim(p_student_id), '') is null then
    raise exception 'student_id required';
  end if;

  select *
    into v_row
  from public.moca_survey_participants
  where student_id = trim(p_student_id);

  if not found or v_row.status <> 'completed' then
    return jsonb_build_object('status', 'not_completed');
  end if;

  if v_row.offline_participated_at is not null then
    return jsonb_build_object(
      'status', 'already_participated',
      'offlineParticipatedAt', v_row.offline_participated_at
    );
  end if;

  return jsonb_build_object(
    'status', 'eligible',
    'studentId', v_row.student_id
  );
end;
$$;

create or replace function public.complete_moca_offline_keyword_match(
  p_student_id text,
  p_answers jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row public.moca_survey_participants%rowtype;
  v_item jsonb;
  v_cafe_index integer;
  v_keywords jsonb;
  v_count integer := 0;
begin
  if auth.uid() is null then
    raise exception 'authentication required';
  end if;

  if nullif(trim(p_student_id), '') is null then
    raise exception 'student_id required';
  end if;

  select *
    into v_row
  from public.moca_survey_participants
  where student_id = trim(p_student_id)
  for update;

  if not found or v_row.status <> 'completed' then
    return jsonb_build_object('status', 'not_completed');
  end if;

  if v_row.offline_participated_at is not null then
    return jsonb_build_object(
      'status', 'already_participated',
      'offlineParticipatedAt', v_row.offline_participated_at
    );
  end if;

  if jsonb_typeof(coalesce(p_answers, '[]'::jsonb)) <> 'array' then
    raise exception 'answers must be a json array';
  end if;

  if jsonb_array_length(coalesce(p_answers, '[]'::jsonb)) <> 6 then
    raise exception 'exactly 6 cafe answers are required';
  end if;

  for v_item in
    select value from jsonb_array_elements(p_answers)
  loop
    v_cafe_index := nullif(v_item->>'cafeIndex', '')::integer;
    v_keywords := coalesce(v_item->'keywords', '[]'::jsonb);

    if v_cafe_index is null or v_cafe_index < 1 or v_cafe_index > 6 then
      raise exception 'invalid cafeIndex';
    end if;

    if jsonb_typeof(v_keywords) <> 'array' then
      raise exception 'keywords must be an array';
    end if;

    if jsonb_array_length(v_keywords) <> 3 then
      raise exception 'exactly 3 keywords per cafe are required';
    end if;

    insert into public.moca_offline_keyword_responses (
      participant_id,
      student_id,
      cafe_index,
      selected_keywords,
      updated_at
    ) values (
      v_row.id,
      v_row.student_id,
      v_cafe_index,
      v_keywords,
      now()
    )
    on conflict (participant_id, cafe_index)
    do update set
      selected_keywords = excluded.selected_keywords,
      student_id = excluded.student_id,
      updated_at = now();

    v_count := v_count + 1;
  end loop;

  if v_count <> 6 then
    raise exception 'failed to save all cafe answers';
  end if;

  update public.moca_survey_participants
  set
    offline_participated_at = now(),
    updated_at = now()
  where id = v_row.id;

  return jsonb_build_object(
    'status', 'completed',
    'offlineParticipatedAt', now()
  );
end;
$$;

revoke all on function public.check_moca_offline_eligibility(text) from public;
revoke all on function public.complete_moca_offline_keyword_match(text,jsonb) from public;

grant execute on function public.check_moca_offline_eligibility(text) to authenticated;
grant execute on function public.complete_moca_offline_keyword_match(text,jsonb) to authenticated;
